name: NASA Project CI

on:
  push:
    branches: [master]
    paths: 
      - '**.yml'
      - node/Nasa-Project/**

  pull_request:
    branches: [master]
    paths: 
      - '**.yml'
      - node/Nasa-Project/**
    
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [17.x, 18.x]
        mongodb-versions: ['4.4','5.0','latest']
    runs-on: ubuntu-latest
    steps:
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.9.0
        with: 
          mongodb-version: ${{matrix.mongodb-version}}
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{matrix.node-version}}
      - run: npm install --prefix node/Nasa-Project
      - run: npm run build --prefix node/Nasa-Project/client
      - run: npm test --prefix node/Nasa-Project
