name: NASA Project CI

on:
  push:
    branches: [master]
    paths: 
      - .github/workflow/**
      - node/Nasa-Project/**

  pull_request:
    branches: [master]
    paths: 
      - .github/workflow/**
      - node/Nasa-Project/**
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version 18
        uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - run: npm install --prefix node/Nasa-Project
      - run: npm run build -prefix node/Nasa-Project/client